version: "3.3"
services:
  web:
    image: mikehearn/shlearn-wedding:latest
    networks:
      - traefik_public
    environment:
      - PORT=8000
    command: node fastboot-server.js
    deploy:
      replicas: 1
      labels:
        - "traefik.backend=http"
        - "traefik.port=8000"
        - "traefik.frontend.rule=PathPrefix:/"
        - "traefik.docker.network=traefik_public"

networks:
  traefik_public:
    external: true
